name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build the JAR file
      run: mvn clean package

    - name: Build the Docker image
      id: build
      run: |
        TIMESTAMP=$(date +%s)
        docker build . --file Dockerfile --tag eureka-server:$TIMESTAMP
        echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Tag Docker image
      run: |
        docker tag eureka-server:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:latest
        docker tag eureka-server:${{ env.TIMESTAMP }} ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:${{ env.TIMESTAMP }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eureka-server:${{ env.TIMESTAMP }}
